<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\JuliMvs.App\JuliMvs.App.csproj" />
    <ProjectReference Include="..\JuliMvs.Core\JuliMvs.Core.csproj" />
    <ProjectReference Include="..\JuliMvs.Vision\JuliMvs.Vision.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
